# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-04 03:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corebib', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autor',
            old_name='cod_a',
            new_name='matricula',
        ),
        migrations.RemoveField(
            model_name='livro',
            name='cod_l',
        ),
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corebib.Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corebib.Editora'),
        ),
    ]
